### ISSUE TITLE
Er is nog wat ruimte voor verbetering op je telefoon.

### ISSUE THREAD

**Issue by Knetters** [DikkeTimo/the-web-is-for-everyone-interactive-functionality#2]
Je zou alle columns die je gebruikt onder elkaar kunnen zetten en een goeie oplossing vinden voor het ontwerp voor de telefoon.

**Comment by TimOosterveer** [comment]
Mobiele versie is nu af, spelers heb ik nu weggehaald omdat het er heel veel zijn(misschien heb jij een idee hoe ik dit het beste kan oplossen?). Thanks voor de issue!
